# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1i_sCAgWqOO-qoafXZlO9WSYDO0gezj93
"""

# [과제 1] Upstage AI Ambassador 지원자 제출 코드
# 주제 : 노년층 및 약자를 위한 실시간 키오스크 주문 도우미
# 작성자 : 주영진

import requests
import json
import os
import textwrap
from openai import OpenAI

# ====================================================================
# [사용 가이드]
# 1. Upstage Console에서 발급받은 API Key를 아래 변수에 입력해주세요.
# 2. 분석할 이미지 파일(예: kiosk.jpg)을 같은 폴더에 업로드해주세요.
# ====================================================================

# 1. API 키 설정
api_key = "YOUR_UPSTAGE_API_KEY_HERE"

# 2. 분석할 이미지 파일명 설정
filename = "/content/test_image1.jpg" # Colab 환경 기준 경로

# 3. 텍스트 줄바꿈 너비 설정 (원하는 크기만큼 설정)
USER_WIDTH = 40
AI_WIDTH = 60

# ===================================================================

client = OpenAI(api_key=api_key, base_url="https://api.upstage.ai/v1/solar")
layout_url = "https://api.upstage.ai/v1/document-ai/layout-analysis"
headers = {"Authorization": f"Bearer {api_key}"}

silver_persona = """
당신은 키오스크 사용이 어려운 어르신을 돕는 '애니원 톡' 비서입니다.
다음 원칙을 지켜주세요:
1. 친절한 상담사 처럼 예의 바르고 다정하게 말씀하세요. (~하세요, ~입니다)
2. 어려운 외래어는 쉽게 풀어서 설명하고, 메뉴의 위치나 가격을 정확히 안내하세요.
3. 답변이 너무 길어지지 않게 핵심만 간단히 말해주세요.
"""

def silver_talk_start():
    print(f"🚀 [애니원 톡] 시스템을 시작합니다...")

    # Step 1 : 이미지 분석 (Document Parse)
    if not os.path.exists(filename):
        print(f"⚠️ 경고: '{filename}' 파일을 찾을 수 없습니다. 테스트할 이미지를 업로드해주세요.")
        return

    print(f"👀 이미지를 분석하고 있습니다... (Document Parse API)")
    try:
        with open(filename, "rb") as f:
            response = requests.post(layout_url, headers=headers, files={"document": f})

        if response.status_code != 200:
            print(f"❌ 분석 실패: API Key를 확인해주세요. (현재 설정: {api_key[:5]}...)")
            return

        scan_result = json.dumps(response.json(), ensure_ascii=False)
        print("✅ 이미지 분석 완료! Solar가 내용을 이해하고 있습니다...\n")
    except Exception as e:
        print(f"❌ 오류 발생: {e}")
        return

    # Step 2 : 요약 및 정리 (Solar LLM)
        summary_prompt = """
    제공된 JSON 데이터를 바탕으로:
    1. [친절한 요약]: 전체 메뉴 종류와 가장 저렴한 메뉴를 3줄 내로 요약해.
    2. [메뉴판 정리]: 메뉴명과 가격을 마크다운 표로 깔끔하게 정리해.
    """

    try:
        summary_response = client.chat.completions.create(
            model="solar-1-mini-chat",
            messages=[
                {"role": "system", "content": silver_persona},
                {"role": "user", "content": f"데이터: {scan_result}\n\n{summary_prompt}"}
            ]
        )
        menu_context = summary_response.choices[0].message.content

        print("="*60)
        print(f"🤖 [애니원 톡]: 어르신, 사진을 보니 이런 메뉴들이 있네요!\n")
        print(menu_context)
        print("="*60)
    except Exception as e:
        print(f"❌ Solar 연결 실패: {e}")
        return

    # Step 3 : 대화 시작 (Interaction)
    print("\n🎤 궁금한 게 있으시면 물어보세요! (종료하려면 '그만' 입력)")

    chat_history = [
        {"role": "system", "content": silver_persona},
        {"role": "system", "content": f"메뉴 정보:\n{scan_result}"},
        {"role": "assistant", "content": menu_context}
    ]

    while True:
        try:
            user_input = input("\n📝 질문 입력: ")
            if user_input.strip() == "그만":
                print("🤖 [애니원 톡]: 네, 조심히 들어가세요!")
                break

            print("\n👵 [어르신]:")
            print(textwrap.fill(user_input, width=USER_WIDTH))

            chat_history.append({"role": "user", "content": user_input})

            answer_response = client.chat.completions.create(
                model="solar-1-mini-chat",
                messages=chat_history
            )

            ai_answer = answer_response.choices[0].message.content

            print("\n🤖 [애니원 톡]:")
            print(textwrap.fill(ai_answer, width=AI_WIDTH))
            print("-" * AI_WIDTH)

            chat_history.append({"role": "assistant", "content": ai_answer})

        except KeyboardInterrupt:
            print("\n종료합니다.")
            break

# 실행 (API Key가 설정되어야 작동합니다)
if __name__ == "__main__":
    if api_key == "YOUR_UPSTAGE_API_KEY_HERE":
        print("⚠️ [알림] 스크립트 상단의 'api_key' 변수에 본인의 API Key를 입력 후 실행해주세요.")
    else:
        silver_talk_start()