# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1i_sCAgWqOO-qoafXZlO9WSYDO0gezj93
"""

# Upstage Solar를 사용하기 위한 도구(OpenAI 라이브러리)를 설치합니다.
!pip install openai

from openai import OpenAI

# 1. Upstage API 키 설정 (따옴표 안에 발급받은 키를 붙여넣으세요)
api_key = "up_1QNAMG6RO2a4itE2aLXO2dohmoaQb"

# 2. Solar 모델과 연결
client = OpenAI(
    api_key=api_key,
    base_url="https://api.upstage.ai/v1/solar"
)

# 3. [핵심] Solar에게 '실버 톡' 역할을 부여하는 설정 (System Prompt)
# 이 부분이 바로 'AI Agent 서비스 기획'의 핵심입니다.
silver_talk_persona = """
당신은 디지털 기기 사용이 낯선 70대 이상 어르신들을 돕는 '친절한 디지털 안내원'입니다.
다음 원칙을 반드시 지켜서 답변하세요:
1. 전문 용어(인터페이스, UX, 클릭 등)는 절대 쓰지 말고, '화면 그림', '누르는 단추'처럼 쉬운 우리말로 풀어서 설명하세요.
2. 마치 손주가 할머니에게 설명하듯 매우 예의 바르고 다정하게, 천천히 설명하는 말투를 쓰세요. (~하셨어요?, ~입니다)
3. 한 번에 너무 많은 정보를 주지 말고, 단계별로 하나씩 알려주세요.
4. 비유를 적극 활용하세요. (예: '키오스크'는 '은행 ATM 기계'와 비슷하다고 설명)
"""

# 4. 대화 함수 만들기
def ask_silver_talk(user_question):
    response = client.chat.completions.create(
        model="solar-1-mini-chat", # Solar 모델 사용
        messages=[
            {"role": "system", "content": silver_talk_persona}, # 역할 주입
            {"role": "user", "content": user_question} # 사용자의 질문
        ]
    )
    return response.choices[0].message.content

# --- 실제 실행 테스트 ---
print("👵 [실버 톡] 안녕하세요, 어르신! 스마트폰이나 기계 쓰시다가 궁금한 게 있으신가요?")

while True:
    question = input("\n질문 입력 (종료하려면 '그만' 입력): ")
    if question == "그만":
        break

    print("\n🤖 솔라의 답변 생각 중...")
    answer = ask_silver_talk(question)
    print(f"\n[실버 톡의 답변]\n{answer}")
    print("-" * 50)

import requests
import json
import os # 파일 확인용 도구 추가

# 1. API 키 (여기에 본인 키를 다시 넣어주세요!)
api_key = "up_1QNAMG6RO2a4itE2aLXO2dohmoaQb"
url = "https://api.upstage.ai/v1/document-ai/layout-analysis"
headers = {"Authorization": f"Bearer {api_key}"}

# [수정된 부분] 파일 이름 앞에 '/content/'를 붙여서 '전체 주소'를 알려줍니다.
filename = "/test_image1.jpg"

# 2. 진짜 파일이 있는지 검사하는 코드 (디버깅용)
if os.path.exists(filename):
    print(f"✅ 파일을 찾았습니다! 경로: {filename}")
else:
    print(f"❌ 여전히 파일을 못 찾고 있습니다. 현재 폴더에 있는 파일들: {os.listdir('/content')}")

# 3. Upstage 눈(Document Parse)으로 이미지 분석 요청
def parse_image(file_path):
    print("👀 이미지를 분석하고 있습니다... (잠시만 기다려주세요)")
    try:
        with open(file_path, "rb") as f:
            response = requests.post(url, headers=headers, files={"document": f})

        if response.status_code == 200:
            print("✅ 분석 완료!")
            return response.json()
        else:
            print(f"❌ 오류 발생: {response.status_code}")
            print(response.text)
            return None
    except FileNotFoundError:
        print("❌ 파일 읽기 실패")
        return None

# --- 실행 ---
# 파일이 확인된 경우에만 실행
if os.path.exists(filename):
    result = parse_image(filename)

    # 결과 맛보기
    if result:
        print("\n[분석 결과 일부]")
        elements = result.get('elements', [])
        for i, element in enumerate(elements[:5]):
            print(f"{i+1}. 찾은 글자: {element['text']}")
            print(f"   위치(좌표): {element['bounding_box']}")

# 1. 방금 읽어온 데이터(result)를 글자로 싹 긁어모으기
# (컴퓨터 언어인 JSON을 Solar가 읽을 수 있는 문자열로 바꿉니다)
import json
raw_data = json.dumps(result, ensure_ascii=False)

# 2. Solar에게 명령할 내용 (프롬프트 엔지니어링)
# 대표님이 원하시는 '표 형태'와 '가격 포함' 요구사항을 여기에 적습니다.
prompt_for_solar = """
너는 키오스크 화면을 읽어주는 친절한 AI 비서야.
내가 키오스크 화면을 분석한 '원시 데이터(JSON)'를 줄 테니까,
이걸 어르신들이 보기 편하게 '메뉴판 표' 형태로 정리해줘.

[반드시 지켜야 할 규칙]
1. 잡다한 시스템 문구(결제하기, 남은시간, EK-192 등)는 다 빼버려.
2. 오직 '메뉴 이름'과 '가격'만 찾아내.
3. 메뉴들을 **한 줄에 4개씩** 배치해서 표(Table)를 만들어줘. (3행 4열 구조야)
4. 가격이 떨어져 있어도, 메뉴 이름 옆에 괄호()로 묶어서 보여줘. 예: 딸기라떼 (3,700원)
5. 가장 위에는 '대분류: 신메뉴', '중분류: 딸기시즌' 이라고 적어줘.
6. 출력 형식은 깔끔한 마크다운 표(Markdown Table)여야 해.
"""

# 3. Solar에게 정리 요청하기
print("🧠 Solar가 메뉴판을 정리하고 있습니다... (두뇌 풀가동!)")

response = client.chat.completions.create(
    model="solar-1-mini-chat",
    messages=[
        {"role": "system", "content": prompt_for_solar},
        {"role": "user", "content": f"이 데이터 좀 정리해줘:\n{raw_data}"}
    ]
)

# 4. 결과 출력
final_output = response.choices[0].message.content
print("\n" + "="*50)
print("     [🍓 어르신을 위한 보기 편한 메뉴판 🍓]")
print("="*50 + "\n")
print(final_output)

import requests
import json
import os
from openai import OpenAI

# ======================================================
# [1] 설정 구역 (여기만 수정하세요!)
# ======================================================
api_key = "up_1QNAMG6RO2a4itE2aLXO2dohmoaQb"  # API 키 필수!
filename = "/test_image1.jpg"       # 분석할 파일 이름 (앞에 / 꼭 붙이기)
# ======================================================

# 준비: Upstage 연결 설정
layout_url = "https://api.upstage.ai/v1/document-ai/layout-analysis"
headers = {"Authorization": f"Bearer {api_key}"}
client = OpenAI(api_key=api_key, base_url="https://api.upstage.ai/v1/solar")

def analyze_and_format():
    # 1단계: 파일이 진짜 있는지 확인
    if not os.path.exists(filename):
        print(f"❌ 오류: '{filename}' 파일을 찾을 수 없습니다.")
        print(f"👉 현재 폴더에 있는 파일들: {os.listdir('/')}")
        return

    # 2단계: 이미지 분석 (Document Parse - 눈)
    print(f"👀 '{filename}' 이미지를 분석 중입니다... (1/2)")
    with open(filename, "rb") as f:
        response = requests.post(layout_url, headers=headers, files={"document": f})

    if response.status_code != 200:
        print("❌ 이미지 분석 실패!")
        print(response.text)
        return

    result = response.json() # 결과를 result 변수에 확실하게 저장!
    print("✅ 이미지 분석 완료! 이제 Solar가 정리를 시작합니다... (2/2)")

    # 3단계: Solar에게 정리 시키기 (Solar - 뇌)
    raw_data = json.dumps(result, ensure_ascii=False)

    prompt = """
    너는 키오스크 화면을 읽어주는 친절한 AI 비서야.
    제공된 JSON 데이터를 바탕으로 메뉴판을 정리해줘.

    [규칙]
    1. 잡다한 시스템 문구는 제외하고 '메뉴명'과 '가격'만 추출해.
    2. 메뉴를 한 줄에 3~4개씩 배치해서 보기 좋은 '마크다운 표'로 만들어.
    3. 가격은 메뉴명 옆에 괄호()로 넣어줘.
    4. 상단에 카테고리(대분류/중분류)가 있다면 적어줘.
    """

    response = client.chat.completions.create(
        model="solar-1-mini-chat",
        messages=[
            {"role": "system", "content": prompt},
            {"role": "user", "content": f"데이터: {raw_data}"}
        ]
    )

    # 4단계: 최종 결과 출력
    print("\n" + "="*50)
    print(f"     [🍓 {filename} 분석 결과 🍓]")
    print("="*50 + "\n")
    print(response.choices[0].message.content)

# --- 실행 ---
analyze_and_format()

# [과제 1] Upstage AI Ambassador 지원자 제출 코드
# 주제 : 노년층을 위한 실시간 키오스크 주문 도우미
# 작성자 : 주영진

import requests
import json
import os
import textwrap
from openai import OpenAI

# ====================================================================
# [사용 가이드]
# 1. Upstage Console에서 발급받은 API Key를 아래 변수에 입력해주세요.
# 2. 분석할 이미지 파일(예: kiosk.jpg)을 같은 폴더에 업로드해주세요.
# ====================================================================

# 1. API 키 설정
api_key = "YOUR_UPSTAGE_API_KEY_HERE"

# 2. 분석할 이미지 파일명 설정
filename = "/content/test_image1.jpg" # Colab 환경 기준 경로

# 3. 텍스트 줄바꿈 너비 설정 (원하는 크기만큼 설정)
USER_WIDTH = 40
AI_WIDTH = 60

# ===================================================================

client = OpenAI(api_key=api_key, base_url="https://api.upstage.ai/v1/solar")
layout_url = "https://api.upstage.ai/v1/document-ai/layout-analysis"
headers = {"Authorization": f"Bearer {api_key}"}

silver_persona = """
당신은 키오스크 사용이 어려운 어르신을 돕는 '실버 톡' 비서입니다.
다음 원칙을 지켜주세요:
1. 손주처럼 예의 바르고 다정하게 말씀하세요. (~하세요, ~입니다)
2. 어려운 외래어는 쉽게 풀어서 설명하고, 메뉴의 위치나 가격을 정확히 안내하세요.
3. 답변이 너무 길어지지 않게 핵심만 간단히 말해주세요.
"""

def silver_talk_start():
    print(f"🚀 [실버 톡] 시스템을 시작합니다...")

    # Step 1 : 이미지 분석 (Document Parse)
    if not os.path.exists(filename):
        print(f"⚠️ 경고: '{filename}' 파일을 찾을 수 없습니다. 테스트할 이미지를 업로드해주세요.")
        return

    print(f"👀 이미지를 분석하고 있습니다... (Document Parse API)")
    try:
        with open(filename, "rb") as f:
            response = requests.post(layout_url, headers=headers, files={"document": f})

        if response.status_code != 200:
            print(f"❌ 분석 실패: API Key를 확인해주세요. (현재 설정: {api_key[:5]}...)")
            return

        scan_result = json.dumps(response.json(), ensure_ascii=False)
        print("✅ 이미지 분석 완료! Solar가 내용을 이해하고 있습니다...\n")
    except Exception as e:
        print(f"❌ 오류 발생: {e}")
        return

    # Step 2 : 요약 및 정리 (Solar LLM)
        summary_prompt = """
    제공된 JSON 데이터를 바탕으로:
    1. [친절한 요약]: 전체 메뉴 종류와 가장 저렴한 메뉴를 3줄 내로 요약해.
    2. [메뉴판 정리]: 메뉴명과 가격을 마크다운 표로 깔끔하게 정리해.
    """

    try:
        summary_response = client.chat.completions.create(
            model="solar-1-mini-chat",
            messages=[
                {"role": "system", "content": silver_persona},
                {"role": "user", "content": f"데이터: {scan_result}\n\n{summary_prompt}"}
            ]
        )
        menu_context = summary_response.choices[0].message.content

        print("="*60)
        print(f"🤖 [실버 톡]: 어르신, 사진을 보니 이런 메뉴들이 있네요!\n")
        print(menu_context)
        print("="*60)
    except Exception as e:
        print(f"❌ Solar 연결 실패: {e}")
        return

    # Step 3 : 대화 시작 (Interaction)
    print("\n🎤 궁금한 게 있으시면 물어보세요! (종료하려면 '그만' 입력)")

    chat_history = [
        {"role": "system", "content": silver_persona},
        {"role": "system", "content": f"메뉴 정보:\n{scan_result}"},
        {"role": "assistant", "content": menu_context}
    ]

    while True:
        try:
            user_input = input("\n📝 질문 입력: ")
            if user_input.strip() == "그만":
                print("🤖 [실버 톡]: 네, 조심히 들어가세요!")
                break

            print("\n👵 [어르신]:")
            print(textwrap.fill(user_input, width=USER_WIDTH))

            chat_history.append({"role": "user", "content": user_input})

            answer_response = client.chat.completions.create(
                model="solar-1-mini-chat",
                messages=chat_history
            )

            ai_answer = answer_response.choices[0].message.content

            print("\n🤖 [실버 톡]:")
            print(textwrap.fill(ai_answer, width=AI_WIDTH))
            print("-" * AI_WIDTH)

            chat_history.append({"role": "assistant", "content": ai_answer})

        except KeyboardInterrupt:
            print("\n종료합니다.")
            break

# 실행 (API Key가 설정되어야 작동합니다)
if __name__ == "__main__":
    if api_key == "YOUR_UPSTAGE_API_KEY_HERE":
        print("⚠️ [알림] 스크립트 상단의 'api_key' 변수에 본인의 API Key를 입력 후 실행해주세요.")
    else:
        silver_talk_start()